### ISSUE TITLE
Using Test::Deep::NoTest before Test::Deep breaks the harness with confusing error

### ISSUE THREAD

**Issue by zbentley** [rjbs/Test-Deep#59]
If I do:

`perl -MTest::Deep::NoTest -MTest::Deep -e 'cmp_deeply(1,1);'`

I would expect the comparison to run via `Test::Builder`. However, what actually happens is:

`Can't call method "ok" on an undefined value at ...lib/perl5/Test/Deep.pm line 204.`

That causes problems. For example, I have a lot of (non-test, production) code that uses Test::Deep::NoTest for comparison functionality without the test harness. If I ever want to test that code, it will fail with that error on the first `Test::Deep` assertion, unless I know to `use Test::Deep` in my test file before I `use` any modules which themselves `use Test::Deep::NoTest`. The error is cryptic enough that this workaround is not obvious.

There are two problems that should be fixed:
- Using `Test::Deep::NoTest` before using `Test::Deep` should not break the harness. Looking briefly at the code, it looks like this is because the `NoTest` module is implemented as a shell that twiddles a global, and the `Test::Deep` module does the heavy lifting. One way to avoid this problem might be to reverse that: to put all the functions in `NoTest`, and the harness bootstrap in the base module.
- Error messages caused by problems with the bootstrapped (or not) harness are cryptic and have no context. `Carp`or similar should probably be used to give stack context around such errors in general.

**Comment by c-ginley** [comment]
This was also an issue for me. `Test::Deep` was not working because our production code uses `Test::Deep::NoTest`. It was not obvious why, and it took digging around the `Test::Deep` code to figure out I just needed to change the order of my `use` statements, to `use Test::Deep` before other modules which might use `Test::Deep::NoTest`.  zbentley has good suggestions for fixing this, or at least making debugging easier.

**Comment by rjbs** [comment]
Fixed by #76 (?)
