### ISSUE TITLE
cmp_deeply issue in perl 5.26.1

### ISSUE THREAD

**Issue by ima23** [rjbs/Test-Deep#65]
Hello,
I'm using cmp_deeply to test expected and observed json structures. It was running fine with perl 5.14, however when I switched to 5.26 it fails due to mismatch of the order of elements in a list within the structure. Is there a way to prevent that or is there an alternative function that I could use? 
Thanks for your advice!

**Comment by karenetheridge** [comment]
It depends on what kinds of structures you are comparing -- can you paste an example?

The difference in behaviour you are observing is due to changes in 5.17.6 -- hashes now return their keys and values in random order, rather than before which appeared random but was a consistent order every time.  *But*, if you are comparing hashes like `cmp_deeply(\%got_hash, { key1 => val1, key2 => val2, ... })` this should still work, as Test::Deep never assumed that hashes have a defined order.

**Comment by ima23** [comment]
Hi @karenetheridge, thanks for your reply. Yes, my structure is a few levels of complexity.
I'm testing a hash of multiple elements, where each element has its own hash with elements and some of these elements are arrays. These arrays are the ones that are retrieved in a random fashion leading to tests failing.  For future, I might have even more nested hashes. 
Currently I have a working test suit using a mix of `bag()` and counts.
```
 {
'key1' => {
        'key1-1' => 'value1',
        'key1-2' => ['value1-2-1', 'value1-2-2']
       }, 
'key2' => {
        'key2-1' => 'value2', 
        'key2-2' => ['value2-2-1', 'value2-2-2', 'value2-2-3']
       }
} 
```

**Comment by karenetheridge** [comment]
`bag()` (or `set()`, if applicable) is definitely the way to go for testing unordered lists.

For unordered tuples, you might find Test::Deep::UnorderedPairs useful, but that sort of data is more rare -- I have mostly only needed it for testing POST parameters coming from an http request.

**Comment by ima23** [comment]
Thanks for the suggestions @karenetheridge! I'll keep them in mind for next time.
