### ISSUE TITLE
cmp_bag() is very slow with large arrays

### ISSUE THREAD

**Issue by petdance** [rjbs/Test-Deep#78]
I did some profiling on some slow tests and was surprised to see that `cmp_bag` took as much as it does.  I did a `cmp_bag` on two 1000-element arrays and it took 14 seconds.

```
use Test::Deep qw( cmp_bag );

use List::Util qw( shuffle );

use Time::HiRes qw( gettimeofday tv_interval );

for my $n ( 1, 10, 100, 1000 ) {
    my @stuff = (1..$n);

    my @shuffled = shuffle @stuff;


    my $cmp_bag  = timer( sub { cmp_bag( \@stuff, \@shuffled ) } );
    my $deep     = timer( sub { is_deeply( [sort @stuff], [sort @shuffled] ) } );

    say "$n items";
    say "cmp_bag  = $cmp_bag";
    say "deep     = $deep";
}



sub timer {
    my $sub = shift;

    my $start = [gettimeofday];

    $sub->();

    return tv_interval( $start );
}
```

And running this looks like:

```
ok 1
ok 2
1 items
cmp_bag  = 0.001496
deep     = 0.000197
ok 3
ok 4
10 items
cmp_bag  = 0.002471
deep     = 0.000191
ok 5
ok 6
100 items
cmp_bag  = 0.161426
deep     = 0.000267
ok 7
ok 8
1000 items
cmp_bag  = 14.842759
deep     = 0.001545
1..8
```

Is this just a case of "Doc it hurts when I go like that?" "Well then don't go like that?" because `cmp_bag()` is overkill for simple arrays of ints?

**Comment by rjbs** [comment]
IMHO:  Don't go like that.

If you can use forced ordering, **by all means do that**.

The issue is that `bag` allows both arbitrary ordering and arbitrary comparison, so it has a backtracking problems.  Say you have tested for `bag(A, B, C)`.  The first two elements in your test data might pass A and B (respectively) so the third must pass C… but it doesn't, so now we might test the first two elements against B and C, then the first against A, etc.

There's a combinatoric problem, here, and if you can avoid it, you should do so.  I believe it's O(N²).  (You could be a real sourpuss and call it O(N⁴) because for every element you add to test, you have to add a test, too.)  Probably this could be significantly improved adding a cache table of which input indexes passed the test in which test index.  A quick glance at the code makes me think this doesn't happen.

**Comment by petdance** [comment]
> IMHO: Don't go like that.

And I'm OK with that.

Since my common use case is "go fetch 1000 integer IDs out of the database and compare them with a different set of 1000", I threw together:

```
=head2 bag_scalars_are( \@got, \@exp [, $msg ] )

Shallow compare of two arrays, ignoring order.

Note that C<bag_scalars_are> is shallow, not deep like C<array_is> or C<cmp_bag>.

=cut

sub bag_scalars_are :prototype($$;$) {
    local $Test::Builder::Level = $Test::Builder::Level + 1;

    my $got = shift;
    my $exp = shift;
    my $msg = shift;

    assert_arrayref( $got );
    assert_arrayref( $exp );

    if ( any { ref } @{$exp} ) {
        return fail( 'None of the expected values passed to bag_scalars_are may be a reference' );
    }

    return is_deeply( [sort_by { $_ // '' } @{$got}], [sort_by { $_ // '' } @{$exp}], $msg );
}
```

I couldn't find anything comparable on CPAN, and this does exactly what I want.

**Comment by rjbs** [comment]
Thanks for letting me know where you ended up!
