### ISSUE TITLE
Support older Perls

### ISSUE THREAD

**Issue by vanHoesel** [rjbs/Test-Deep#87]
I understand that there are some interesting features out there that people should start using in more modern Perls.

But since this module is part of `Test::Most`, pipelines will start breaking. Your 'convenience' has become an inconvenience for others.

Please point me out what the true technical concerns are to stop supporting Perls before 5.12. And even worse, your notes suggest that this will go up... and up... and up.

`Test::Deep` is not core Perl, but using `Test::Most` has been strongly encouraged.

Please, fix this.

**Comment by karenetheridge** [comment]
> using Test::Most has been strongly encouraged

By whom? I've been actively discouraging it ever since encountering https://rt.cpan.org/Ticket/Display.html?id=100213.

Nevertheless, the older releases of Test::Deep are not going away - they are still available via PAUSE or backpan.

**Comment by rjbs** [comment]
> Please, fix this.

I refuse.

**Comment by vanHoesel** [comment]
> By whom? I've been actively discouraging it ever since encountering https://rt.cpan.org/Ticket/Display.html?id=100213.

That issue has been fixed long ago, isn't it ?

**Comment by vanHoesel** [comment]
> By whom? I've been actively discouraging it ever since

Even if it is not been encouraged, or maybe discouraged to use it, I can't see it as a polite way to force people in revisiting their code because pipelines start to fail.

I don't want to abuse MetaCPAN to grep for `Test::Most`, but anything that has been using it, and want to add a bit of automated testing and GitHub workflow CI, is now at risk. And people start to wonder why their code is not passing tests on systems running older perls. Test that prior to to `0200` just used to pass.

This is just going to be a headache, and a waste of human brain cycles... and why ?

**Comment by vanHoesel** [comment]
> I refuse

@rjbs , you mind elaborating on that ?

**Comment by vanHoesel** [comment]
I would hate to see that out of the last 35 commits, only 202ed25 would have added some 'interesting' change. And that all the other 34 were just about tooling around this code.

I hope that there is more reason than just tooling behind your 'I refuse' to keep this 5.6.x backward compatible.

**Comment by rjbs** [comment]
I don't want to think about v5.8, let alone v5.6.  They are ancient beyond my consideration.  Anyone still running them, in my opinion, should accept that the maintenance cost will go up over time as people move on to new versions.  How long until I should feel free to use a new version even for trivial reasons?  I am going to say that for myself, the answer isn't clear, but it is clearly *less than thirteen years*.

https://rjbs.cloud/blog/2023/01/leaving-perl-v5.8-behind/

Even the extremely conservative toolchain policy has been updated, this year, so that things like Test::More and ExtUtils::MakeMaker may update to v5.16, and next year that will be v5.20.
